"use client";

import { useActionState, useCallback, useEffect, useMemo, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Activity, AlertTriangle, Beaker, CheckCircle2, ChevronRight, CircleDot, Clock3, FileSearch, FlaskConical, LoaderCircle, Plus, Search, Settings2, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Modal, ModalFooter, ModalSection } from "@/components/ui/modal";
import { useToast } from "@/components/ui/toast";
import { createDiagnosticOrderAction, saveDiagnosticResultAction, saveDiagnosticsPreferencesAction, transitionDiagnosticOrderAction, type DiagnosticsActionState } from "@/features/diagnostics/actions";
import { formatCpf } from "@/lib/formatters";
import type { DiagnosticItem, DiagnosticOrder, DiagnosticsWorkspace as WorkspaceData } from "@/repositories/diagnostics";

const inputClass = "h-9 w-full rounded-md border bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring";
const textareaClass = "min-h-24 w-full rounded-md border bg-background px-3 py-2 text-sm leading-5 outline-none focus-visible:ring-2 focus-visible:ring-ring";
const sections = [
  ["overview", "Central"], ["orders", "Pedidos"], ["results", "Resultados"], ["alerts", "Alertas"], ["reports", "Relatórios"], ["preferences", "Preferências"],
] as const;

const statusLabels: Record<string, string> = { draft: "Rascunho", requested: "Solicitado", scheduled: "Agendado", collected: "Coletado", in_progress: "Em processamento", partial: "Resultado parcial", completed: "Concluído", cancelled: "Cancelado", corrected: "Corrigido" };
const categoryLabels: Record<string, string> = { laboratory: "Laboratório", imaging: "Imagem", pathology: "Patologia", functional: "Funcional", other: "Outro" };
const priorityLabels: Record<string, string> = { routine: "Rotina", urgent: "Urgente", stat: "Imediato" };
const flagLabels: Record<string, string> = { normal: "Normal", low: "Abaixo", high: "Acima", critical: "Crítico", indeterminate: "Indeterminado" };

function useActionToast(state: DiagnosticsActionState, done?: () => void) {
  const { toast } = useToast(); const handled = useRef("");
  useEffect(() => { const key = `${state.error}:${state.success}:${state.recordId}`; if (handled.current === key || key === "undefined:undefined:undefined") return; handled.current = key; if (state.error) toast({ title: "Ação não concluída", description: state.error, variant: "destructive" }); if (state.success) { toast({ title: "Central diagnóstica", description: state.success }); done?.(); } }, [done, state, toast]);
}

function statusClass(status: string) {
  if (status === "completed") return "bg-emerald-500/10 text-emerald-700";
  if (["cancelled", "corrected"].includes(status)) return "bg-destructive/10 text-destructive";
  if (["partial", "in_progress", "collected"].includes(status)) return "bg-sky-500/10 text-sky-700";
  return "bg-amber-500/10 text-amber-700";
}

function dateTime(value?: string | null) { return value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "Não informado"; }

type DraftItem = { code_system: "internal" | "tuss" | "loinc"; procedure_code: string; name: string; specimen: string; instructions: string; sort_order: number };

function NewOrderModal({ open, onOpenChange, data }: { open: boolean; onOpenChange: (value: boolean) => void; data: WorkspaceData }) {
  const router = useRouter(); const [state, action, pending] = useActionState(createDiagnosticOrderAction, {});
  const [appointmentId, setAppointmentId] = useState(""); const [patientId, setPatientId] = useState(""); const [professionalId, setProfessionalId] = useState(""); const [encounterId, setEncounterId] = useState("");
  const [items, setItems] = useState<DraftItem[]>([{ code_system: "tuss", procedure_code: "", name: "", specimen: "", instructions: "", sort_order: 0 }]);
  const done = useCallback(() => { onOpenChange(false); router.refresh(); }, [onOpenChange, router]); useActionToast(state, done);
  function selectAppointment(id: string) { const appointment = data.appointments.find((item) => item.id === id); setAppointmentId(id); setPatientId(appointment?.patient_id ?? ""); setProfessionalId(appointment?.professional_member_id ?? ""); setEncounterId(appointment?.encounter_id ?? ""); }
  function patchItem(index: number, patch: Partial<DraftItem>) { setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item)); }
  return <Modal open={open} onOpenChange={onOpenChange} title="Novo pedido diagnóstico" description="Pedido clínico estruturado, vinculado ao atendimento e preparado para resultados versionados." size="xl">
    <form action={action} className="grid gap-4">
      <input type="hidden" name="appointment_id" value={appointmentId} /><input type="hidden" name="encounter_id" value={encounterId} /><input type="hidden" name="items" value={JSON.stringify(items)} />
      <ModalSection className="grid gap-3">
        <div className="grid gap-3 lg:grid-cols-3">
          <label className="grid gap-1.5 text-xs font-medium">Atendimento relacionado<select value={appointmentId} onChange={(event) => selectAppointment(event.target.value)} className={inputClass}><option value="">Pedido avulso</option>{data.appointments.map((item) => <option key={item.id} value={item.id}>{dateTime(item.starts_at)}</option>)}</select></label>
          <label className="grid gap-1.5 text-xs font-medium">Paciente<select name="patient_id" value={patientId} onChange={(event) => { setPatientId(event.target.value); setAppointmentId(""); setEncounterId(""); }} className={inputClass} required><option value="">Selecione</option>{data.patients.map((item) => <option key={item.id} value={item.id}>{item.social_name || item.full_name} {item.cpf ? `· ${formatCpf(item.cpf)}` : ""}</option>)}</select></label>
          <label className="grid gap-1.5 text-xs font-medium">Profissional solicitante<select name="professional_member_id" value={professionalId} onChange={(event) => setProfessionalId(event.target.value)} className={inputClass} required><option value="">Selecione</option>{data.professionals.map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label>
        </div>
        <div className="grid gap-3 lg:grid-cols-3"><label className="grid gap-1.5 text-xs font-medium">Categoria<select name="category" className={inputClass}>{Object.entries(categoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1.5 text-xs font-medium">Prioridade<select name="priority" className={inputClass}><option value="routine">Rotina</option><option value="urgent">Urgente</option><option value="stat">Imediato</option></select></label><label className="grid gap-1.5 text-xs font-medium">Agendamento previsto<input name="scheduled_at" type="datetime-local" className={inputClass} /></label></div>
        <label className="grid gap-1.5 text-xs font-medium">Indicação clínica<textarea name="clinical_indication" className={textareaClass} placeholder="Hipótese, sinais, sintomas e objetivo da investigação" required /></label>
        <label className="grid gap-1.5 text-xs font-medium">Preparo e jejum<textarea name="fasting_instructions" className={`${textareaClass} min-h-16`} /></label>
      </ModalSection>
      <ModalSection className="grid gap-3"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Exames solicitados</p><p className="text-xs text-muted-foreground">Use TUSS ou LOINC quando disponível para interoperabilidade.</p></div><Button type="button" variant="outline" size="sm" onClick={() => setItems((current) => [...current, { code_system: "tuss", procedure_code: "", name: "", specimen: "", instructions: "", sort_order: current.length }])}><Plus />Adicionar exame</Button></div>
        <div className="grid gap-2">{items.map((item, index) => <div key={index} className="grid gap-2 rounded-md border bg-muted/10 p-2.5 lg:grid-cols-[110px_130px_1fr_150px_auto]"><select value={item.code_system} onChange={(event) => patchItem(index, { code_system: event.target.value as DraftItem["code_system"] })} className={inputClass}><option value="tuss">TUSS</option><option value="loinc">LOINC</option><option value="internal">Interno</option></select><input value={item.procedure_code} onChange={(event) => patchItem(index, { procedure_code: event.target.value })} className={inputClass} placeholder="Código" /><input value={item.name} onChange={(event) => patchItem(index, { name: event.target.value })} className={inputClass} placeholder="Nome do exame" required /><input value={item.specimen} onChange={(event) => patchItem(index, { specimen: event.target.value })} className={inputClass} placeholder="Material/amostra" /><Button type="button" variant="ghost" disabled={items.length === 1} onClick={() => setItems((current) => current.filter((_, itemIndex) => itemIndex !== index))}>Remover</Button></div>)}</div>
      </ModalSection>
      <ModalFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={pending || !patientId || !professionalId || items.some((item) => !item.name.trim())}><FlaskConical />{pending ? "Criando..." : "Confirmar pedido"}</Button></ModalFooter>
    </form>
  </Modal>;
}

function ResultModal({ order, item, open, onOpenChange, canApprove }: { order: DiagnosticOrder; item: DiagnosticItem; open: boolean; onOpenChange: (value: boolean) => void; canApprove: boolean }) {
  const router = useRouter(); const [state, action, pending] = useActionState(saveDiagnosticResultAction, {}); const current = item.results.find((result) => ["preliminary", "final"].includes(result.status));
  const done = useCallback(() => { onOpenChange(false); router.refresh(); }, [onOpenChange, router]); useActionToast(state, done);
  return <Modal open={open} onOpenChange={onOpenChange} title={item.name} description={`${order.order_number} · resultado versionado e integrado ao prontuário`} size="lg"><form action={action} className="grid gap-4"><input type="hidden" name="order_item_id" value={item.id} />
    <div className="grid gap-3 lg:grid-cols-2"><label className="grid gap-1.5 text-xs font-medium">Resultado textual<input name="value_text" defaultValue={current?.value_text ?? ""} className={inputClass} /></label><div className="grid grid-cols-2 gap-2"><label className="grid gap-1.5 text-xs font-medium">Valor numérico<input name="value_numeric" type="number" step="any" defaultValue={current?.value_numeric ?? ""} className={inputClass} /></label><label className="grid gap-1.5 text-xs font-medium">Unidade<input name="unit" defaultValue={current?.unit ?? ""} className={inputClass} /></label></div><label className="grid gap-1.5 text-xs font-medium">Referência<input name="reference_range" defaultValue={current?.reference_range ?? ""} className={inputClass} /></label><label className="grid gap-1.5 text-xs font-medium">Sinalização<select name="flag" defaultValue={current?.flag ?? "normal"} className={inputClass}>{Object.entries(flagLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
    <label className="grid gap-1.5 text-xs font-medium">Interpretação<textarea name="interpretation" defaultValue={current?.interpretation ?? ""} className={textareaClass} /></label><label className="grid gap-1.5 text-xs font-medium">Laudo<textarea name="report_text" defaultValue={current?.report_text ?? ""} className={`${textareaClass} min-h-40`} /></label>{current?.status === "final" ? <label className="grid gap-1.5 text-xs font-medium text-destructive">Motivo da correção<input name="correction_reason" className={inputClass} required minLength={5} /></label> : null}
    <ModalFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button type="submit" name="status" value="preliminary" variant="outline" disabled={pending}>Salvar preliminar</Button><Button type="submit" name="status" value="final" disabled={pending || !canApprove}><CheckCircle2 />Validar resultado</Button></ModalFooter>
  </form></Modal>;
}

function OrderTable({ orders, data }: { orders: DiagnosticOrder[]; data: WorkspaceData }) {
  const router = useRouter(); const [selected, setSelected] = useState<{ order: DiagnosticOrder; item: DiagnosticItem } | null>(null); const [transitionOrder, setTransitionOrder] = useState<DiagnosticOrder | null>(null);
  const [state, action, pending] = useActionState(transitionDiagnosticOrderAction, {}); const done = useCallback(() => { setTransitionOrder(null); router.refresh(); }, [router]); useActionToast(state, done);
  return <><div className="overflow-x-auto rounded-md border"><table className="w-full min-w-[1040px] text-[13px]"><thead className="sticky top-0 bg-muted/80 text-left text-xs text-muted-foreground backdrop-blur"><tr><th className="px-3 py-2">Pedido</th><th className="px-3 py-2">Paciente</th><th className="px-3 py-2">Tipo</th><th className="px-3 py-2">Etapa</th><th className="px-3 py-2">Exames</th><th className="px-3 py-2">Atualização</th><th className="sticky right-0 bg-muted px-3 py-2 text-right">Ações</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-t hover:bg-muted/20"><td className="px-3 py-2.5"><p className="selectable font-mono text-xs font-medium">{order.order_number}</p><p className="mt-1 text-[11px] text-muted-foreground">{priorityLabels[order.priority]}</p></td><td className="px-3 py-2.5 font-medium">{order.patient?.social_name || order.patient?.full_name}</td><td className="px-3 py-2.5">{categoryLabels[order.category]}</td><td className="px-3 py-2.5"><Badge className={statusClass(order.status)}>{statusLabels[order.status]}</Badge></td><td className="px-3 py-2.5"><div className="flex flex-wrap gap-1">{order.items.slice(0, 3).map((item) => <button key={item.id} type="button" onClick={() => setSelected({ order, item })} disabled={!data.access.canEdit} className="rounded border bg-background px-2 py-1 text-[11px] hover:border-primary/50">{item.name}</button>)}{order.items.length > 3 ? <span className="px-1 py-1 text-[11px] text-muted-foreground">+{order.items.length - 3}</span> : null}</div></td><td className="px-3 py-2.5 text-xs text-muted-foreground">{dateTime(order.completed_at || order.collected_at || order.created_at)}</td><td className="sticky right-0 bg-card px-3 py-2.5 text-right"><Button variant="ghost" size="sm" onClick={() => setTransitionOrder(order)} disabled={!data.access.canEdit}>Atualizar <ChevronRight /></Button></td></tr>)}</tbody></table>{orders.length === 0 ? <div className="grid h-36 place-items-center text-sm text-muted-foreground">Nenhum pedido encontrado para os filtros atuais.</div> : null}</div>
    {selected ? <ResultModal order={selected.order} item={selected.item} open onOpenChange={(value) => !value && setSelected(null)} canApprove={data.access.canApprove || data.access.canManage} /> : null}
    {transitionOrder ? <Modal open onOpenChange={(value) => !value && setTransitionOrder(null)} title="Atualizar etapa" description={`${transitionOrder.order_number} · alterações excepcionais exigem justificativa`} size="sm"><form action={action} className="grid gap-3"><input type="hidden" name="order_id" value={transitionOrder.id} /><label className="grid gap-1.5 text-xs font-medium">Nova etapa<select name="next_status" className={inputClass}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1.5 text-xs font-medium">Motivo, quando aplicável<textarea name="reason" className={textareaClass} /></label><ModalFooter><Button type="button" variant="outline" onClick={() => setTransitionOrder(null)}>Cancelar</Button><Button disabled={pending}>Confirmar alteração</Button></ModalFooter></form></Modal> : null}
  </>;
}

export function DiagnosticsWorkspace({ data, section, query, status }: { data: WorkspaceData; section: string; query: string; status: string }) {
  const router = useRouter(); const [isNavigating, startNavigation] = useTransition(); const [orderOpen, setOrderOpen] = useState(false); const normalized = query.toLocaleLowerCase("pt-BR");
  const filtered = useMemo(() => data.orders.filter((order) => (status === "all" || order.status === status) && (!normalized || order.order_number.toLowerCase().includes(normalized) || order.patient?.full_name.toLocaleLowerCase("pt-BR").includes(normalized) || order.items.some((item) => item.name.toLocaleLowerCase("pt-BR").includes(normalized)))), [data.orders, normalized, status]);
  const critical = data.orders.flatMap((order) => order.items.flatMap((item) => item.results.filter((result) => result.flag === "critical").map((result) => ({ order, item, result }))));
  const metrics = [{ label: "Em andamento", value: data.orders.filter((item) => !["completed", "cancelled"].includes(item.status)).length, icon: Activity }, { label: "Aguardando resultado", value: data.orders.filter((item) => ["collected", "in_progress", "partial"].includes(item.status)).length, icon: Clock3 }, { label: "Concluídos", value: data.orders.filter((item) => item.status === "completed").length, icon: CheckCircle2 }, { label: "Alertas críticos", value: critical.length, icon: AlertTriangle }];
  function navigateUrl(url: string) { startNavigation(() => router.push(url)); }
  function navigate(nextSection: string) { navigateUrl(`/exames?section=${nextSection}`); }
  return <div className="relative grid gap-4 pb-10" aria-busy={isNavigating}>
    {isNavigating ? <div className="fixed inset-x-0 top-12 z-50 h-0.5 overflow-hidden bg-primary/15"><div className="h-full w-1/3 animate-pulse bg-primary" /></div> : null}
    <section className="relative overflow-hidden rounded-md border bg-card px-4 py-4"><div className="absolute inset-y-0 left-0 w-1 bg-primary" /><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-md bg-primary/10 text-primary"><Beaker className="size-4" /></span><div><h1 className="text-lg font-semibold">Exames e diagnóstico</h1><p className="text-xs text-muted-foreground">Do pedido ao resultado validado, com contexto clínico e rastreabilidade.</p></div></div></div>{data.access.canCreate ? <Button onClick={() => setOrderOpen(true)}><Plus />Novo pedido</Button> : null}</div></section>
    <div className="sticky top-12 z-20 flex items-center justify-between gap-3 rounded-md border bg-background/90 p-1.5 shadow-sm backdrop-blur-xl"><nav className="flex items-center gap-1">{sections.map(([key, label]) => <button key={key} onClick={() => navigate(key)} disabled={isNavigating} className={`h-8 rounded px-3 text-xs font-medium ${section === key ? "bg-foreground text-background" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{label}</button>)}</nav><div className="flex items-center gap-2 text-xs text-muted-foreground">{isNavigating ? <><LoaderCircle className="size-3.5 animate-spin text-primary" />Carregando visão</> : <><Sparkles className="size-3.5 text-primary" />Fluxo clínico conectado</>}</div></div>
    <section className="grid grid-cols-4 divide-x rounded-md border bg-card">{metrics.map((metric) => <div key={metric.label} className="flex items-center gap-3 px-4 py-3"><metric.icon className="size-4 text-muted-foreground" /><div><p className="text-xl font-semibold tabular-nums">{metric.value}</p><p className="text-[11px] text-muted-foreground">{metric.label}</p></div></div>)}</section>
    {section !== "preferences" ? <div className="flex items-center gap-2 rounded-md border bg-card p-2"><div className="relative min-w-72 flex-1"><Search className="pointer-events-none absolute left-3 top-2.5 size-4 text-muted-foreground" /><input defaultValue={query} onKeyDown={(event) => { if (event.key === "Enter") navigateUrl(`/exames?section=${section}&status=${status}&query=${encodeURIComponent(event.currentTarget.value)}`); }} className={`${inputClass} pl-9`} placeholder="Pedido, paciente ou exame" /></div><select value={status} disabled={isNavigating} onChange={(event) => navigateUrl(`/exames?section=${section}&status=${event.target.value}&query=${encodeURIComponent(query)}`)} className="h-9 w-48 rounded-md border bg-background px-3 text-xs"><option value="all">Todas as etapas</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Button variant="outline" size="sm"><Settings2 />Mais filtros</Button></div> : null}
    <div className={isNavigating ? "pointer-events-none opacity-55 transition-opacity" : "contents"}>
    {section === "overview" || section === "orders" ? <OrderTable orders={filtered} data={data} /> : null}
    {section === "results" ? <OrderTable orders={filtered.filter((order) => order.items.some((item) => item.results.length))} data={data} /> : null}
    {section === "alerts" ? <div className="overflow-hidden rounded-md border bg-card"><div className="border-b px-4 py-3"><p className="text-sm font-semibold">Resultados que exigem atenção</p><p className="text-xs text-muted-foreground">A sinalização apoia a priorização e não substitui avaliação profissional.</p></div>{critical.map(({ order, item, result }) => <div key={result.id} className="grid grid-cols-[1fr_1fr_160px] items-center gap-3 border-b px-4 py-3 last:border-0"><div><p className="text-sm font-medium">{order.patient?.full_name}</p><p className="text-xs text-muted-foreground">{order.order_number}</p></div><div><p className="text-sm font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{result.value_text || `${result.value_numeric ?? "-"} ${result.unit ?? ""}`}</p></div><Badge className="justify-center bg-destructive/10 text-destructive">Crítico</Badge></div>)}{critical.length === 0 ? <div className="grid h-36 place-items-center text-sm text-muted-foreground">Nenhum alerta crítico ativo.</div> : null}</div> : null}
    {section === "reports" ? <div className="grid grid-cols-3 gap-3"><div className="rounded-md border bg-card p-4"><FileSearch className="size-5 text-primary" /><p className="mt-3 text-sm font-semibold">Produção diagnóstica</p><p className="mt-1 text-xs text-muted-foreground">Pedidos por categoria, profissional, prazo e desfecho.</p></div><div className="rounded-md border bg-card p-4"><CircleDot className="size-5 text-primary" /><p className="mt-3 text-sm font-semibold">Tempo de resposta</p><p className="mt-1 text-xs text-muted-foreground">Intervalos entre solicitação, coleta e validação.</p></div><div className="rounded-md border bg-card p-4"><AlertTriangle className="size-5 text-primary" /><p className="mt-3 text-sm font-semibold">Indicadores críticos</p><p className="mt-1 text-xs text-muted-foreground">Alertas, correções e rastreabilidade clínica.</p></div></div> : null}
    {section === "preferences" ? <PreferencesForm preferences={data.preferences} /> : null}
    </div>
    <NewOrderModal open={orderOpen} onOpenChange={setOrderOpen} data={data} />
  </div>;
}

function PreferencesForm({ preferences }: { preferences: Record<string, unknown> }) {
  const [state, action, pending] = useActionState(saveDiagnosticsPreferencesAction, {}); useActionToast(state);
  return <form action={action} className="overflow-hidden rounded-md border bg-card"><header className="border-b px-4 py-3"><p className="text-sm font-semibold">Minha estação diagnóstica</p><p className="text-xs text-muted-foreground">Essas escolhas valem somente para seu usuário nesta clínica.</p></header><div className="grid max-w-3xl gap-4 p-4"><div className="grid grid-cols-2 gap-3"><label className="grid gap-1.5 text-xs font-medium">Tela inicial<select name="default_section" defaultValue={String(preferences.defaultSection ?? "overview")} className={inputClass}>{sections.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1.5 text-xs font-medium">Densidade<select name="density" defaultValue={String(preferences.density ?? "compact")} className={inputClass}><option value="compact">Compacta</option><option value="comfortable">Confortável</option></select></label></div><label className="grid gap-1.5 text-xs font-medium">Filtro de etapa favorito<select name="saved_status" defaultValue={String(preferences.savedStatus ?? "all")} className={inputClass}><option value="all">Todas</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="flex items-center justify-between rounded-md border p-3 text-sm"><span><b className="block text-sm">Destacar resultados críticos</b><span className="text-xs text-muted-foreground">Mantém alertas clínicos em evidência.</span></span><input type="checkbox" name="highlight_critical" defaultChecked={preferences.highlightCritical !== false} /></label><label className="flex items-center justify-between rounded-md border p-3 text-sm"><span><b className="block text-sm">Abrir resultado após salvar</b><span className="text-xs text-muted-foreground">Agiliza conferência em rotinas sequenciais.</span></span><input type="checkbox" name="auto_open_result" defaultChecked={preferences.autoOpenResult === true} /></label></div><footer className="flex justify-end border-t px-4 py-3"><Button disabled={pending}>{pending ? "Salvando..." : "Salvar preferências"}</Button></footer></form>;
}
