"use client";

import { useActionState, useEffect } from "react";
import { BookOpen, FileText, LockKeyhole, Save, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/components/ui/toast";
import { createDataSubjectRequestAction, saveComplianceSettingsAction, type ComplianceActionState } from "@/features/compliance/actions";
import type { ComplianceSettings, DataSubjectRequest } from "@/repositories/compliance";

const requestLabels: Record<DataSubjectRequest["request_type"], string> = { access: "Acesso", export: "Exportação", rectification: "Retificação", deletion: "Exclusão", restriction: "Restrição" };
const statusLabels: Record<DataSubjectRequest["status"], string> = { open: "Aberta", in_review: "Em análise", completed: "Concluída", rejected: "Recusada" };

export function ComplianceWorkspace({ settings, requests, canEdit }: { settings: ComplianceSettings | null; requests: DataSubjectRequest[]; canEdit: boolean }) {
  const [settingsState, settingsAction, settingsPending] = useActionState<ComplianceActionState, FormData>(saveComplianceSettingsAction, {});
  const [requestState, requestAction, requestPending] = useActionState<ComplianceActionState, FormData>(createDataSubjectRequestAction, {});
  const { toast } = useToast();
  useEffect(() => { if (settingsState.error || settingsState.success) toast({ title: settingsState.error ? "Conformidade não salva" : "Conformidade", description: settingsState.error ?? settingsState.success, variant: settingsState.error ? "destructive" : "default" }); }, [settingsState, toast]);
  useEffect(() => { if (requestState.error || requestState.success) toast({ title: requestState.error ? "Solicitação não registrada" : "Solicitação LGPD", description: requestState.error ?? requestState.success, variant: requestState.error ? "destructive" : "default" }); }, [requestState, toast]);
  return <div className="grid gap-5">
    <section className="grid gap-3 rounded-md border bg-card p-4"><div className="flex items-start gap-3"><div className="grid size-9 place-items-center rounded-md bg-primary/10 text-primary"><LockKeyhole className="size-4" /></div><div><p className="text-sm font-semibold">Conformidade, privacidade e continuidade</p><p className="mt-1 max-w-3xl text-xs leading-5 text-muted-foreground">Centralize a política operacional da clínica, solicitações de titulares e incidentes. O sistema registra cada alteração na auditoria. Os textos jurídicos públicos são uma base e devem ser revisados por um profissional habilitado.</p></div></div><div className="flex flex-wrap gap-2 text-xs"><a className="inline-flex items-center gap-1.5 rounded border px-2.5 py-1.5 hover:bg-muted" href="/termos" target="_blank" rel="noreferrer"><FileText className="size-3.5" /> Termos de uso</a><a className="inline-flex items-center gap-1.5 rounded border px-2.5 py-1.5 hover:bg-muted" href="/privacidade" target="_blank" rel="noreferrer"><BookOpen className="size-3.5" /> Política de privacidade</a><a className="inline-flex items-center gap-1.5 rounded border px-2.5 py-1.5 hover:bg-muted" href="/ajuda" target="_blank" rel="noreferrer"><ShieldAlert className="size-3.5" /> Central de ajuda</a></div></section>
    <Card><CardHeader><CardTitle>Política da clínica</CardTitle><CardDescription>Defina retenção, responsável e canais que serão usados em suporte e incidentes.</CardDescription></CardHeader><CardContent><form action={settingsAction} className="grid gap-3 lg:grid-cols-4"><label className="grid gap-1.5 text-xs font-medium">Retenção em dias<input type="number" name="retention_days" min="30" max="3650" defaultValue={settings?.retention_days ?? 1825} disabled={!canEdit || settingsPending} className="h-9 rounded-md border bg-background px-3 text-sm font-normal" /></label><label className="grid gap-1.5 text-xs font-medium">Responsável<input name="responsible_name" defaultValue={settings?.responsible_name ?? ""} disabled={!canEdit || settingsPending} className="h-9 rounded-md border bg-background px-3 text-sm font-normal" /></label><label className="grid gap-1.5 text-xs font-medium">E-mail de suporte<input type="email" name="support_email" defaultValue={settings?.support_email ?? ""} disabled={!canEdit || settingsPending} className="h-9 rounded-md border bg-background px-3 text-sm font-normal" /></label><label className="grid gap-1.5 text-xs font-medium">E-mail de incidentes<input type="email" name="incident_email" defaultValue={settings?.incident_email ?? ""} disabled={!canEdit || settingsPending} className="h-9 rounded-md border bg-background px-3 text-sm font-normal" /></label><div className="lg:col-span-4 flex justify-end"><Button disabled={!canEdit || settingsPending}><Save /> {settingsPending ? "Salvando..." : "Salvar política"}</Button></div></form></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><Card><CardHeader><CardTitle>Registrar solicitação do titular</CardTitle><CardDescription>Confirme a identidade antes de entregar qualquer dado pessoal.</CardDescription></CardHeader><CardContent><form action={requestAction} className="grid gap-3"><label className="grid gap-1.5 text-xs font-medium">Tipo<select name="request_type" defaultValue="access" className="h-9 rounded-md border bg-background px-3 text-sm font-normal"><option value="access">Acesso</option><option value="export">Exportação</option><option value="rectification">Retificação</option><option value="deletion">Exclusão</option><option value="restriction">Restrição</option></select></label><label className="grid gap-1.5 text-xs font-medium">Nome do titular<input name="requester_name" className="h-9 rounded-md border bg-background px-3 text-sm font-normal" /></label><label className="grid gap-1.5 text-xs font-medium">Contato para validação<input name="requester_contact" className="h-9 rounded-md border bg-background px-3 text-sm font-normal" placeholder="E-mail ou telefone" /></label><label className="grid gap-1.5 text-xs font-medium">Descrição<textarea name="description" className="min-h-20 rounded-md border bg-background px-3 py-2 text-sm font-normal" /></label><Button disabled={requestPending}><ShieldAlert /> {requestPending ? "Registrando..." : "Registrar solicitação"}</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Solicitações registradas</CardTitle><CardDescription>{requests.length} solicitação(ões) no histórico da clínica.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-[13px]"><thead className="bg-muted/50 text-left text-[11px] uppercase text-muted-foreground"><tr><th className="px-3 py-2">Titular</th><th className="px-3 py-2">Tipo</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Registro</th></tr></thead><tbody>{requests.map((request) => <tr key={request.id} className="border-t"><td className="px-3 py-2"><p className="font-medium">{request.requester_name}</p><p className="text-xs text-muted-foreground">{request.requester_contact}</p></td><td className="px-3 py-2">{requestLabels[request.request_type]}</td><td className="px-3 py-2"><Badge>{statusLabels[request.status]}</Badge></td><td className="px-3 py-2 text-xs text-muted-foreground">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(request.created_at))}</td></tr>)}{!requests.length ? <tr><td colSpan={4} className="px-3 py-8 text-center text-xs text-muted-foreground">Nenhuma solicitação registrada.</td></tr> : null}</tbody></table></div></CardContent></Card></div>
  </div>;
}
