"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { getActiveClinicContext } from "@/features/clinics/context";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export type InsuranceActionState = { error?: string; success?: string; recordId?: string };
async function context() { const [{ activeClinic }, supabase] = await Promise.all([getActiveClinicContext(), createSupabaseServerClient()]); const { data: { user } } = await supabase.auth.getUser(); return activeClinic && user ? { activeClinic, user, supabase } : null; }
function errorMessage(message?: string) { const value = message?.toUpperCase() ?? ""; if (value.includes("PERMISSION") || value.includes("APPROVAL")) return "Seu perfil não possui permissão para esta operação TISS."; if (value.includes("PATIENT")) return "Paciente inválido para a clínica ativa."; if (value.includes("HEALTH_PLAN")) return "Convênio inválido ou inativo."; if (value.includes("ITEMS_REQUIRED")) return "Inclua ao menos um procedimento na guia."; if (value.includes("NOT_READY")) return "Todas as guias do lote precisam estar prontas e pertencer ao mesmo convênio."; if (value.includes("INVALID_TRANSITION")) return "Essa mudança de etapa não é permitida."; if (value.includes("REASON_REQUIRED")) return "Informe o motivo da correção, negativa ou cancelamento."; return "Não foi possível concluir a operação de convênio."; }

export async function saveCoverageAction(_: InsuranceActionState, formData: FormData): Promise<InsuranceActionState> { const parsed = z.object({ id: z.string().uuid().nullable(), patient_id: z.string().uuid(), health_plan_id: z.string().uuid(), beneficiary_number: z.string().trim().min(3).max(80), plan_name: z.string().trim().max(120).nullable(), accommodation: z.string().trim().max(80).nullable(), validity_date: z.string().nullable(), holder_name: z.string().trim().max(160).nullable(), holder_document: z.string().trim().max(20).nullable(), is_primary: z.boolean() }).safeParse({ id: formData.get("id") || null, patient_id: formData.get("patient_id"), health_plan_id: formData.get("health_plan_id"), beneficiary_number: formData.get("beneficiary_number"), plan_name: formData.get("plan_name") || null, accommodation: formData.get("accommodation") || null, validity_date: formData.get("validity_date") || null, holder_name: formData.get("holder_name") || null, holder_document: formData.get("holder_document") || null, is_primary: formData.get("is_primary") === "on" }); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Revise a cobertura." }; const ctx = await context(); if (!ctx) return { error: "Sessão inválida." }; const { data, error } = await ctx.supabase.rpc("save_patient_coverage_transaction", { coverage_payload: { clinic_id: ctx.activeClinic.id, ...parsed.data } }); if (error || !data) return { error: errorMessage(error?.message) }; revalidatePath("/convenios"); return { success: "Cobertura salva e disponível para novas guias.", recordId: data as string }; }

export async function createTissGuideAction(_: InsuranceActionState, formData: FormData): Promise<InsuranceActionState> { let items: unknown; try { items = JSON.parse(String(formData.get("items") ?? "[]")); } catch { return { error: "Procedimentos inválidos." }; } const parsed = z.object({ health_plan_id: z.string().uuid(), coverage_id: z.string().uuid().nullable(), patient_id: z.string().uuid(), appointment_id: z.string().uuid().nullable(), encounter_id: z.string().uuid().nullable(), professional_member_id: z.string().uuid().nullable(), financial_entry_id: z.string().uuid().nullable(), guide_type: z.enum(["consultation", "sadt", "hospitalization", "fees", "dental"]), status: z.enum(["draft", "pending_authorization", "authorized", "ready"]), authorization_number: z.string().trim().max(80).nullable(), authorization_valid_until: z.string().nullable(), service_date: z.string(), clinical_indication: z.string().trim().max(3000).nullable(), notes: z.string().trim().max(1000).nullable(), items: z.array(z.object({ tuss_code: z.string().trim().min(2).max(30), description: z.string().trim().min(2).max(180), service_date: z.string(), quantity: z.number().positive(), unit_amount_cents: z.number().int().nonnegative() })).min(1) }).safeParse({ health_plan_id: formData.get("health_plan_id"), coverage_id: formData.get("coverage_id") || null, patient_id: formData.get("patient_id"), appointment_id: formData.get("appointment_id") || null, encounter_id: formData.get("encounter_id") || null, professional_member_id: formData.get("professional_member_id") || null, financial_entry_id: formData.get("financial_entry_id") || null, guide_type: formData.get("guide_type"), status: formData.get("status"), authorization_number: formData.get("authorization_number") || null, authorization_valid_until: formData.get("authorization_valid_until") || null, service_date: formData.get("service_date"), clinical_indication: formData.get("clinical_indication") || null, notes: formData.get("notes") || null, items }); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Revise a guia." }; const ctx = await context(); if (!ctx) return { error: "Sessão inválida." }; const { data, error } = await ctx.supabase.rpc("save_tiss_guide_transaction", { guide_payload: { clinic_id: ctx.activeClinic.id, ...parsed.data } }); if (error || !data) return { error: errorMessage(error?.message) }; revalidatePath("/convenios"); revalidatePath("/financeiro"); return { success: "Guia criada e incluída no fluxo TISS.", recordId: data as string }; }

export async function transitionTissGuideAction(_: InsuranceActionState, formData: FormData): Promise<InsuranceActionState> { const parsed = z.object({ guide_id: z.string().uuid(), next_status: z.string().min(2), reason: z.string().trim().max(500).nullable() }).safeParse({ guide_id: formData.get("guide_id"), next_status: formData.get("next_status"), reason: formData.get("reason") || null }); if (!parsed.success) return { error: "Transição inválida." }; const ctx = await context(); if (!ctx) return { error: "Sessão inválida." }; const { error } = await ctx.supabase.rpc("transition_tiss_guide_transaction", { guide_uuid: parsed.data.guide_id, next_status: parsed.data.next_status, transition_reason: parsed.data.reason }); if (error) return { error: errorMessage(error.message) }; revalidatePath("/convenios"); return { success: "Etapa da guia atualizada." }; }

export async function createTissBatchAction(_: InsuranceActionState, formData: FormData): Promise<InsuranceActionState> { const guideIds = formData.getAll("guide_ids").map(String); const parsed = z.object({ health_plan_id: z.string().uuid(), competence: z.string().regex(/^\d{4}-\d{2}$/), tiss_version: z.string().min(4), guide_ids: z.array(z.string().uuid()).min(1) }).safeParse({ health_plan_id: formData.get("health_plan_id"), competence: formData.get("competence"), tiss_version: formData.get("tiss_version"), guide_ids: guideIds }); if (!parsed.success) return { error: "Selecione convênio, competência e ao menos uma guia pronta." }; const ctx = await context(); if (!ctx) return { error: "Sessão inválida." }; const { data, error } = await ctx.supabase.rpc("create_tiss_batch_transaction", { batch_payload: { clinic_id: ctx.activeClinic.id, ...parsed.data } }); if (error || !data) return { error: errorMessage(error?.message) }; revalidatePath("/convenios"); return { success: "Lote validado e fechado para transmissão.", recordId: data as string }; }

export async function saveInsurancePreferencesAction(_: InsuranceActionState, formData: FormData): Promise<InsuranceActionState> { const ctx = await context(); if (!ctx) return { error: "Sessão inválida." }; const preferences = { defaultSection: String(formData.get("default_section") || "overview"), defaultPlanId: String(formData.get("default_plan_id") || ""), density: String(formData.get("density") || "compact"), savedGuideStatus: String(formData.get("saved_guide_status") || "all"), warnExpiringAuthorization: formData.get("warn_expiring_authorization") === "on" }; const { error } = await ctx.supabase.rpc("save_module_user_preferences", { module_name: "insurance", preference_payload: { clinic_id: ctx.activeClinic.id, preferences } }); if (error) return { error: "Não foi possível salvar suas preferências." }; revalidatePath("/convenios"); return { success: "Preferências pessoais salvas." }; }
