import "server-only";

import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { getClinicAuthorization } from "@/services/authorization/clinic-access";

export type InsuranceAccess = { canView: boolean; canCreate: boolean; canEdit: boolean; canApprove: boolean; canManage: boolean; canExport: boolean };
export type HealthPlanOption = { id: string; name: string; ans_registration: string | null; tiss_version: string; operator_code: string | null; submission_deadline_days: number };
export type Coverage = { id: string; beneficiary_number: string; plan_name: string | null; validity_date: string | null; is_primary: boolean; active: boolean; patient: { id: string; full_name: string; social_name: string | null; cpf: string | null } | null; health_plan: HealthPlanOption | null };
export type TissGuide = { id: string; guide_number: string; operator_guide_number: string | null; guide_type: string; status: string; authorization_number: string | null; service_date: string; total_cents: number; approved_cents: number; paid_cents: number; glossed_cents: number; clinical_indication: string | null; created_at: string; patient: { id: string; full_name: string; social_name: string | null } | null; health_plan: HealthPlanOption | null; items: Array<{ id: string; tuss_code: string; description: string; quantity: number; unit_amount_cents: number; requested_cents: number; approved_cents: number; paid_cents: number; glossed_cents: number; status: string; gloss_code: string | null; gloss_reason: string | null }> };
export type TissBatch = { id: string; batch_number: string; competence: string; tiss_version: string; status: string; guide_count: number; total_cents: number; protocol_number: string | null; submitted_at: string | null; created_at: string; health_plan: HealthPlanOption | null };
export type InsuranceWorkspace = { access: InsuranceAccess; healthPlans: HealthPlanOption[]; coverages: Coverage[]; guides: TissGuide[]; batches: TissBatch[]; patients: Array<{ id: string; full_name: string; social_name: string | null; cpf: string | null }>; appointments: Array<{ id: string; patient_id: string; professional_member_id: string; starts_at: string; encounter_id: string | null; service_id: string | null }>; financialEntries: Array<{ id: string; patient_id: string | null; appointment_id: string | null; description: string; amount_cents: number; status: string }>; professionals: Array<{ id: string; full_name: string }>; services: Array<{ id: string; name: string; code: string | null; price_cents: number }>; preferences: Record<string, unknown> };

export async function getInsuranceAccess(clinicId?: string | null): Promise<InsuranceAccess> { const auth = await getClinicAuthorization(clinicId ?? undefined); return { canView: auth.can("insurance", "view"), canCreate: auth.can("insurance", "create"), canEdit: auth.can("insurance", "edit"), canApprove: auth.can("insurance", "approve"), canManage: auth.can("insurance", "manage"), canExport: auth.can("insurance", "export") }; }

export async function getInsuranceWorkspace(clinicId?: string | null): Promise<InsuranceWorkspace> {
  const access = await getInsuranceAccess(clinicId); const empty: InsuranceWorkspace = { access, healthPlans: [], coverages: [], guides: [], batches: [], patients: [], appointments: [], financialEntries: [], professionals: [], services: [], preferences: {} }; if (!clinicId || !access.canView) return empty;
  const auth = await getClinicAuthorization(clinicId); const admin = createSupabaseAdminClient();
  const [{ data: healthPlans }, { data: coverages }, { data: guides }, { data: batches }, { data: patients }, { data: appointments }, { data: encounters }, { data: financialEntries }, { data: professionals }, { data: services }, { data: preference }] = await Promise.all([
    admin.from("financial_health_plans").select("id, name, ans_registration, tiss_version, operator_code, submission_deadline_days").eq("clinic_id", clinicId).eq("active", true).is("deleted_at", null).order("name"),
    admin.from("patient_health_coverages").select("id, beneficiary_number, plan_name, validity_date, is_primary, active, patient:patients(id, full_name, social_name, cpf), health_plan:financial_health_plans(id, name, ans_registration, tiss_version, operator_code, submission_deadline_days)").eq("clinic_id", clinicId).is("deleted_at", null).order("created_at", { ascending: false }).limit(250),
    admin.from("tiss_guides").select("id, guide_number, operator_guide_number, guide_type, status, authorization_number, service_date, total_cents, approved_cents, paid_cents, glossed_cents, clinical_indication, created_at, patient:patients(id, full_name, social_name), health_plan:financial_health_plans(id, name, ans_registration, tiss_version, operator_code, submission_deadline_days), items:tiss_guide_items(id, tuss_code, description, quantity, unit_amount_cents, requested_cents, approved_cents, paid_cents, glossed_cents, status, gloss_code, gloss_reason)").eq("clinic_id", clinicId).is("deleted_at", null).order("created_at", { ascending: false }).limit(200),
    admin.from("tiss_batches").select("id, batch_number, competence, tiss_version, status, guide_count, total_cents, protocol_number, submitted_at, created_at, health_plan:financial_health_plans(id, name, ans_registration, tiss_version, operator_code, submission_deadline_days)").eq("clinic_id", clinicId).is("deleted_at", null).order("created_at", { ascending: false }).limit(120),
    access.canCreate ? admin.from("patients").select("id, full_name, social_name, cpf").eq("clinic_id", clinicId).eq("active", true).is("deleted_at", null).order("full_name").limit(400) : Promise.resolve({ data: [] }),
    access.canCreate ? admin.from("appointments").select("id, patient_id, professional_member_id, starts_at, service_id").eq("clinic_id", clinicId).is("deleted_at", null).order("starts_at", { ascending: false }).limit(250) : Promise.resolve({ data: [] }),
    access.canCreate ? admin.from("clinical_encounters").select("id, appointment_id").eq("clinic_id", clinicId).is("deleted_at", null).limit(250) : Promise.resolve({ data: [] }),
    access.canCreate ? admin.from("financial_entries").select("id, patient_id, appointment_id, description, amount_cents, status").eq("clinic_id", clinicId).eq("entry_type", "receivable").is("deleted_at", null).order("created_at", { ascending: false }).limit(250) : Promise.resolve({ data: [] }),
    access.canCreate ? admin.from("clinic_members").select("id, profile:profiles!clinic_members_user_id_fkey(full_name)").eq("clinic_id", clinicId).eq("status", "active").is("deleted_at", null).in("role", ["clinic_owner", "doctor", "professional"]) : Promise.resolve({ data: [] }),
    admin.from("clinic_services").select("id, name, code, price_cents").eq("clinic_id", clinicId).eq("active", true).is("deleted_at", null).order("name"),
    auth.userId ? admin.from("module_user_preferences").select("preferences").eq("clinic_id", clinicId).eq("user_id", auth.userId).eq("module_key", "insurance").is("deleted_at", null).maybeSingle<{ preferences: Record<string, unknown> }>() : Promise.resolve({ data: null }),
  ]);
  const encounterMap = new Map((encounters ?? []).map((row) => [row.appointment_id, row.id]));
  return { access, healthPlans: (healthPlans ?? []) as HealthPlanOption[], coverages: (coverages ?? []) as unknown as Coverage[], guides: (guides ?? []) as unknown as TissGuide[], batches: (batches ?? []) as unknown as TissBatch[], patients: patients ?? [], appointments: (appointments ?? []).map((item) => ({ ...item, encounter_id: encounterMap.get(item.id) ?? null })), financialEntries: financialEntries ?? [], professionals: (professionals ?? []).map((member) => ({ id: member.id, full_name: (member.profile as unknown as { full_name?: string } | null)?.full_name ?? "Profissional" })), services: services ?? [], preferences: preference?.preferences ?? {} };
}
